config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('users/', include('users.urls', namespace='users')),
    path('services/', include('services.urls', namespace='services')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main.apps import MainConfig
from main.views import IndexTemplateView, AboutTemplateView, ContactsTemplateView, feedback

app_name = MainConfig.name

urlpatterns = [
    path('', IndexTemplateView.as_view(), name='index'),
    path('about/', AboutTemplateView.as_view(), name='about'),
    path('contacts/', ContactsTemplateView.as_view(), name='contacts'),
    path('feedback/', feedback, name='feedback')
]

services/urls.py
from django.urls import path

from services.apps import ServicesConfig
from services.views import DoctorCreateView, DoctorListView, DoctorDetailView, DoctorUpdateView, DoctorDeleteView, \
    AppointmentCreateView, AppointmentListView, AppointmentDetailView, AppointmentUpdateView, AppointmentDeleteView, \
    AnalysisCreateView, AnalysisListView, AnalysisDetailView, AnalysisUpdateView, AnalysisDeleteView, ResultCreateView, \
    ResultListView, ResultDetailView, ResultUpdateView, ResultDeleteView

app_name = ServicesConfig.name


urlpatterns = [
    path('doctor/create/', DoctorCreateView.as_view(), name='doctor_create'),
    path('doctor/list/', DoctorListView.as_view(), name='doctor_list'),
    path('doctor/detail/<int:pk>/', DoctorDetailView.as_view(), name='doctor_detail'),
    path('doctor/update/<int:pk>/', DoctorUpdateView.as_view(), name='doctor_update'),
    path('doctor/delete/<int:pk>/', DoctorDeleteView.as_view(), name='doctor_delete'),

    path('appointment/create/', AppointmentCreateView.as_view(), name='appointment_create'),
    path('appointment/list/', AppointmentListView.as_view(), name='appointment_list'),
    path('appointment/detail/<int:pk>/', AppointmentDetailView.as_view(), name='appointment_detail'),
    path('appointment/update/<int:pk>/', AppointmentUpdateView.as_view(), name='appointment_update'),
    path('appointment/delete/<int:pk>/', AppointmentDeleteView.as_view(), name='appointment_delete'),

    path('analysis/create/', AnalysisCreateView.as_view(), name='analysis_create'),
    path('analysis/list/', AnalysisListView.as_view(), name='analysis_list'),
    path('analysis/detail/<int:pk>/', AnalysisDetailView.as_view(), name='analysis_detail'),
    path('analysis/update/<int:pk>/', AnalysisUpdateView.as_view(), name='analysis_update'),
    path('analysis/delete/<int:pk>/', AnalysisDeleteView.as_view(), name='analysis_delete'),

    path('result/create/', ResultCreateView.as_view(), name='result_create'),
    path('result/list/', ResultListView.as_view(), name='result_list'),
    path('result/detail/<int:pk>/', ResultDetailView.as_view(), name='result_detail'),
    path('result/update/<int:pk>/', ResultUpdateView.as_view(), name='result_update'),
    path('result/delete/<int:pk>/', ResultDeleteView.as_view(), name='result_delete'),
]

users/urls.py
from users.apps import UsersConfig

from django.urls import path
from django.contrib.auth.views import LogoutView
from users.views import UserLoginView, UserRegister, email_verification, UserProfile, UserProfileUpdate, CartListView, \
    add_to_cart, HistoryListView, delete_from_cart, HistoryDetailView, RequestCreateView, pay_cache

app_name = UsersConfig.name

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserRegister.as_view(), name='register'),
    path('email-confirm/<str:token>/', email_verification, name='email_confirm'),

    path('profile/', UserProfile.as_view(), name='profile'),
    path('change-profile/', UserProfileUpdate.as_view(), name='profile_update'),

    path('cart/', CartListView.as_view(), name='cart'),
    path('add_to_cart/', add_to_cart, name='add_to_cart'),
    path('delete_from_cart/', delete_from_cart, name='delete_from_cart'),
    path('pay_cache/', pay_cache, name='pay_cache'),

    path('history/', HistoryListView.as_view(), name='history'),
    path('history/detail/<int:pk>/', HistoryDetailView.as_view(), name='history_detail'),

    path('request/create/', RequestCreateView.as_view(), name='request_create'),
]

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from django.forms import ModelForm

from main.forms import StyleFormMixin
from users.models import User, Request


class UserLoginForm(StyleFormMixin, AuthenticationForm):
    pass


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    """Форма для создания объекта модели User."""

    class Meta:
        model = User
        fields = ('email', 'fullname', 'phone_number', 'password1', 'password2',)


class UserProfileUpdateForm(StyleFormMixin, UserChangeForm):
    """Форма для редактирования объекта модели User."""

    class Meta:
        model = User
        fields = ('fullname', 'phone_number',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].widget = forms.HiddenInput()


class RequestDateInput(forms.DateInput):
    input_type = 'date'


class RequestModelForm(StyleFormMixin, ModelForm):
    """Форма для создания/редактирования объекта модели Request."""

    class Meta:
        model = Request
        exclude = ('owner', 'fullname', 'phone_number', 'email',)
        widgets = {
            'date': RequestDateInput(),
        }

users/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import Group
from django.contrib.auth.views import LoginView
from django.core.exceptions import PermissionDenied
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, UpdateView, ListView

from services.models import Analysis, Appointment, UsersAppointment
from users.forms import UserLoginForm, UserRegisterForm, UserProfileUpdateForm, RequestModelForm
from users.models import User, Cart, History, Request
from users.services import send_email_verification, convert_to_history


# Контроллеры относящиеся к модели User #############################
class UserLoginView(LoginView):
    """Контроллер для логина пользователя."""
    template_name = 'users/login.html'
    form_class = UserLoginForm

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Авторизация'
        return context_data


class UserRegister(CreateView):
    """Контроллер для регистрации пользователя."""
    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy('main:index')

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        user.save()
        send_email_verification(self, user)
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Регистрация'
        return context_data


def email_verification(request, token):
    """Находит пользователя по токену из ссылки, выдает группу user и активирует пользователя."""
    user = get_object_or_404(User, token=token)

    user_group = Group.objects.get(name='user')
    user_group.user_set.add(user)

    user.is_active = True
    user.save()
    return redirect('users:login')


class UserProfile(LoginRequiredMixin, DetailView):
    """Контроллер просмотра профиля пользователя."""
    model = User
    template_name = 'users/profile.html'

    def get_object(self, queryset=None):
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Профиль'
        return context


class UserProfileUpdate(LoginRequiredMixin, UpdateView):
    """Контроллер редактирования профиля пользователя."""
    model = User
    form_class = UserProfileUpdateForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Редактирование профиля'
        return context


# Контроллеры относящиеся к модели Cart #############################
def get_cart_info(object_list):
    cart_count = 0
    cart_sum = 0

    if object_list is not None:
        cart_count = len(object_list)
        for obj in object_list:
            if obj.analysis:
                cart_sum += obj.analysis.price
            else:
                cart_sum += obj.users_appointment.get_service().price

    return cart_count, cart_sum


class CartListView(LoginRequiredMixin, ListView):
    """Контроллер для отображения списка объектов модели Cart."""
    model = Cart

    def get_context_data(self, *, object_list=None, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Корзина'

        user = self.request.user
        if user.groups.filter(name='user').exists():
            object_list = Cart.objects.filter(owner=user)
            context_data['object_list'] = object_list

            cart_count, cart_sum = get_cart_info(object_list)
            context_data['cart_count'] = cart_count
            context_data['cart_sum'] = cart_sum
            return context_data

        cart_count, cart_sum = get_cart_info(object_list)
        context_data['cart_count'] = cart_count
        context_data['cart_sum'] = cart_sum
        return context_data


@login_required
def add_to_cart(request):
    """Добавляет анализ или прием в корзину."""

    user = request.user
    obj_class = request.GET['type']

    if obj_class == 'analysis':
        pk = request.GET['id']

        Cart.objects.create(
            owner=user,
            analysis=Analysis.objects.get(pk=pk)
        )

        return HttpResponse(status=201)

    if obj_class == 'appointment':
        pk = request.GET['appointment_id']
        appointment = Appointment.objects.get(pk=pk)
        service_id = request.GET['service_id']

        users_appointment = UsersAppointment.objects.create(
            owner=user,
            title=appointment.title,
            doctor=appointment.doctor,
            date_time=appointment.date_time,
            service_id=service_id
        )

        Cart.objects.create(
            owner=user,
            users_appointment=users_appointment
        )

        return HttpResponse(status=201)


@login_required
def delete_from_cart(request):
    """Удаляет объекты из корзины."""

    user = request.user
    pk = request.GET['id']

    Cart.objects.get(owner=user, pk=pk).delete()

    return HttpResponse(status=204)


@login_required
def pay_cache(request):
    """Для оплаты наличными, просто переносит услуги из корзины в историю."""

    convert_to_history(request)

    return HttpResponse(status=200)


# Контроллеры относящиеся к модели History ##########################
class HistoryListView(LoginRequiredMixin, ListView):
    """Контроллер для отображения списка объектов модели History."""
    model = History

    def get_context_data(self, *, object_list=None, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'История'

        user = self.request.user
        if user.groups.filter(name='user').exists():
            object_list = History.objects.filter(owner=user)
            context_data['object_list'] = object_list
            return context_data
        return context_data


class HistoryDetailView(LoginRequiredMixin, DetailView):
    """Контроллер для отображения объекта модели History."""
    model = History

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        user = self.request.user

        if user.groups.filter(name='user').exists():
            if user == self.object.owner:
                self.object.save()
                return self.object
            raise PermissionDenied

        self.object.save()
        return self.object

    def get_context_data(self, *, object_list=None, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'История'
        return context_data


# Контроллеры относящиеся к модели Request ##########################
class RequestCreateView(LoginRequiredMixin, CreateView):
    """Контроллер для создания объекта модели Request."""
    model = Request
    form_class = RequestModelForm
    success_url = reverse_lazy('users:profile')

    def form_valid(self, form):
        user = self.request.user
        request_obj = form.save()

        request_obj.owner = user
        request_obj.fullname = user.fullname
        request_obj.phone_number = user.phone_number
        request_obj.email = user.email

        request_obj.save()
        return super().form_valid(form)

    def get_context_data(self, *, object_list=None, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Запись на прием'
        return context_data

users/templates/users/cart_list.html
{% extends 'main/base.html' %}
{% load custom_tags %}

{% block content %}
<div class="container mt-3">
  <div class="row">
    <div class="list-group p-0">
      <div class="list-group-item mb-2" style="min-height: 50px">
        <div class="row">
          <div class="col-10">
            <div class="d-flex w-100 justify-content-between">
              <h4>Услуг к оплате: {{ cart_count }}</h4>
              <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#paymentModal">
                Перейти к оплате
              </button>
            </div>

            <div class="modal fade" id="paymentModal" tabindex="-1" aria-labelledby="paymentModalLabel"
                 aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <h1 class="modal-title fs-5" id="paymentModalLabel">Выберите способ оплаты</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                  </div>
                  <div class="modal-body">
                    <button class="btn btn-outline-success" type="button" onclick="pay_cache()" aria-label="Close">
                      Наличными
                    </button>
                  </div>
                </div>
              </div>
            </div>

          </div>
          <div class="col-2 text-end">
            <div class="d-flex justify-content-between h-100">
              <div class="vr"
                   style="position: absolute; left: 83%; top: 0; bottom: 0; width: 1px; background-color: #ccc;"></div>

              <div class="d-flex w-100 justify-content-between">
                <h4>Сумма: {{ cart_sum }} ₽</h4>
              </div>

            </div>
          </div>
        </div>
      </div>
    </div>
    {% for object in object_list %}
    <div class="list-group p-0">

      <div class="list-group-item mb-2" style="min-height: 75px">
        <div class="row">
          <div class="col-10">
              {% if object.analysis %}
                <div class="d-flex w-100 justify-content-between">
                <h5>{{ object.analysis.title }}</h5>
                <small class="text-muted">Анализ</small>
              </div>
              {% endif %}
              {% if object.users_appointment %}
                <div class="d-flex w-100 justify-content-between">
                  <div>
                    <h5>{{ object.users_appointment.title }}</h5>
                    {{ object.users_appointment.get_service }}
                  </div>
                <small class="text-muted">Прием</small>
              </div>
              {% endif %}
          </div>

          <div class="col-2 text-end">
            <div class="d-flex justify-content-between h-100">
              <div class="vr"
                   style="position: absolute; left: 83%; top: 0; bottom: 0; width: 1px; background-color: #ccc;"></div>

              <div class="d-flex w-100 justify-content-between">
                {% if object.analysis %}
                <h4 class="mb-1">{{ object.analysis.price }} ₽</h4>
                {% endif %}
                {% if object.users_appointment %}
                <h4 class="mb-1">{{ object.users_appointment.get_service.price }} ₽</h4>
                {% endif %}
                <button class="btn btn-danger ps-4 pe-4" onclick="delete_from_cart({{ object.pk }})">
                  <h3>-</h3>
                </button>
              </div>

            </div>
          </div>

        </div>
      </div>

    </div>
    {% endfor %}
  </div>
</div>

<script>
  function delete_from_cart(id) {
      fetch("{% url 'users:delete_from_cart' %}?id="+id, {method: 'GET',}).then(response => {
      });
      location.reload();
    }

  function pay_cache() {
      fetch("{% url 'users:pay_cache' %}", {method: 'GET',}).then(response => {
      });
      window.location.href = '{{ host }}/users/cart';
  }
</script>

{% endblock %}

users/templates/users/history_detail.html
{% extends 'main/base.html' %}
{% load custom_tags %}

{% block content %}
<div class="container mt-3">
  <div class="row">

    <h6>Дата и время оплаты</h6>
    {{ object.payment_daytime }}
    <hr>
    <h6>Информация о приеме</h6>
    {{ object.service_info }}
    <hr>
    <h6>Информация о результате</h6>
    {% if object.result %}
    {{ object.result.title }}<br>
    {{ object.result.message }}
    {% else %}
    Результат ещё не готов
    {% endif %}
    <hr>
    <h6>Стоимость</h6>
    {{ object.price }} ₽


  </div>
{% endblock %}

users/templates/users/history_list.html
{% extends 'main/base.html' %}
{% load custom_tags %}

{% block content %}
<div class="container mt-3">
  <div class="row">
    {% for object in object_list %}
      <div class="list-group p-0">

        <div class="list-group-item mb-2" style="min-height: 120px">
          <div class="row">
            <div class="col-10">
              <h5 class="mb-1">
                {{ object.payment_daytime }} <a class="btn btn-info" href="{% url 'users:history_detail' object.pk %}">Подробнее</a> <br>
                {{ object.service_info|truncatechars:85 }}<br>
                {% if object.result %}
                <a href="{% url 'services:result_detail' object.result.pk %}">{{ object.result.title|truncatechars:85 }}</a>
                {% else %}
                Результат ещё не готов
                {% endif %}
              </h5>
              <p class="mb-1">
                {{ object.description|truncatechars:250 }}<br>
              </p>
            </div>

            <div class="col-2 text-end">
              <div class="d-flex justify-content-between h-100">
                <div class="vr"
                     style="position: absolute; left: 83%; top: 0; bottom: 0; width: 1px; background-color: #ccc;"></div>

                <div class="d-flex w-100 justify-content-between">
                  <h4 class="mb-1">{{ object.price }} ₽</h4>
                </div>

              </div>
            </div>

          </div>
        </div>

      </div>
      {% endfor %}
  </div>
</div>
{% endblock %}

users/templates/users/login.html
{% extends 'main/base.html' %}
{% block content %}
<div class="container col-4">
  <div class="card mt-5">
    <form method="post" enctype="multipart/form-data">
      <div class="card-body">
        {% csrf_token %}
        {{ form.as_p }}
      </div>
      <div class="card-footer">
        <div class="row">
          <div class="col-6">
            <button class="btn btn-outline-success col-12" type="submit">Войти</button>
          </div>
          <div class="col-6">
            <a class="btn btn-outline-secondary col-12" href="{% url 'main:index' %}">На главную</a>
          </div>
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock %}

users/templates/users/profile.html
{% extends 'main/base.html' %}
{% load custom_tags %}

{% block content %}
<div class="container col-6">
<a class="btn btn-outline-info col-12" href="{% url 'users:request_create' %}">Записаться на прием</a>
  <div class="card mt-3">
    {% if object.fullname %}
    <div class="card-header">
      <h4>{{ object.fullname }}</h4>
    </div>
    {% endif %}
    <div class="card-body">
      <div class="row">
        <div class="col-4">
          <img src="{{ object.avatar | media_filter }}" style="width: 12rem; height: 12rem;" border="1px solid #555">
        </div>
        <div class=" col-8">
          Почта: {{ object.email }}<br>
          Телефон: {{ object.phone_number }}
        </div>
      </div>
    </div>
    <div class="card-footer">
      <div class="row">
        <div class="col-6 p-1">
          <a class="btn btn-outline-success col-12" href="{% url 'users:profile_update' %}">Редактировать профиль</a>
        </div>
        <div class="col-6 p-1">
          <a class="btn btn-outline-secondary col-12" href="{% url 'main:index' %}">На главную</a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

users/templates/users/request_form.html
{% extends 'main/base.html' %}
{% block content %}

<p>
  Вы можете оформить заявку на платный прием и диагностику на сайте через форму, приведенную ниже.
</p>
<hr>
<div class="row">
  <div class="col-3">
    <h6>ПРИЕМ ЗАЯВОК ПО ГРАФИКУ</h6>
    <table class="table table-bordered">
      <tbody>
      <tr>
        <td scope="col">ПН-ПТ</td>
        <td scope="col">08:00-18:00</td>
      </tr>
      <tr>
        <td scope="col">Суббота</td>
        <td scope="col">09:00-14:00</td>
      </tr>
      <tr>
        <td scope="col">Воскресенье</td>
        <td scope="col">Выходной</td>
      </tr>
      </tbody>
    </table>
  </div>
  <div class="col-9">
    <p>
      После оформления заявки с вами свяжется оператор, согласует день и время приема;<br>
      Заявки, оформленные внерабочее время, обрабатываются на следующий рабочий день в порядке очереди;<br>
      Если в списке нет нужного вам специалиста, то запись к нему осуществляется по тел. 8 (343) 351-76-05;<br>
      Отказаться от приема можно, выбрав в форме онлайн-записи пункт "отменить прием" или позвонив по телефону 8 (343)
      351-76-05.
    </p>
  </div>
</div>

<div class="container col-6">
  <div class="card mt-2">
    <div class="card-header">
      <h5 class="text-center">Заявка на запись</h5>
    </div>
    <form method="post">
      <div class="card-body">
        {% csrf_token %}
        {{ form.as_p }}
      </div>
      <div class="card-footer">
        <div class="row col-12">
          <div class="col-6 p-1">
            <button class="btn btn-outline-success col-12">Отправить</button>
          </div>
          <div class="col-6 p-1">
            <a class="btn btn-outline-secondary col-12" href="{% url 'users:profile' %}">Личный кабинет</a>
          </div>
        </div>
      </div>
    </form>
  </div>
</div>

{% endblock %}

users/templates/users/user_form.html
{% extends 'main/base.html' %}
{% block content %}
<div class="container col-6">
  <div class="card mt-5">
    {% if object.fullname %}
    <div class="card-header">
      <h4>{{ object.fullname }}</h4>
    </div>
    {% endif %}
    <form method="post">
      <div class="card-body">
        {% csrf_token %}
        {{ form.as_p }}
      </div>
      <div class="card-footer">
        <div class="row col-12">
          {% if object %}
          <div class="col-6 p-1">
            <button class="btn btn-outline-success col-12">Сохранить изменения</button>
          </div>
          {% else %}
          <div class="col-6 p-1">
            <button class="btn btn-outline-success col-12">Зарегистрироваться</button>
          </div>
          {% endif %}
          <div class="col-6 p-1">
            <a class="btn btn-outline-secondary col-12" href="{% url 'main:index' %}">На главную</a>
          </div>
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock %}