config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('users/', include('users.urls', namespace='users')),
    path('services/', include('services.urls', namespace='services')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main.apps import MainConfig
from main.views import IndexTemplateView, AboutTemplateView, ContactsTemplateView, feedback

app_name = MainConfig.name

urlpatterns = [
    path('', IndexTemplateView.as_view(), name='index'),
    path('about/', AboutTemplateView.as_view(), name='about'),
    path('contacts/', ContactsTemplateView.as_view(), name='contacts'),
    path('feedback/', feedback, name='feedback')
]

services/urls.py
from django.urls import path

from services.apps import ServicesConfig
from services.views import DoctorCreateView, DoctorListView, DoctorDetailView, DoctorUpdateView, DoctorDeleteView, \
    AppointmentCreateView, AppointmentListView, AppointmentDetailView, AppointmentUpdateView, AppointmentDeleteView, \
    AnalysisCreateView, AnalysisListView, AnalysisDetailView, AnalysisUpdateView, AnalysisDeleteView, ResultCreateView, \
    ResultListView, ResultDetailView, ResultUpdateView, ResultDeleteView

app_name = ServicesConfig.name


urlpatterns = [
    path('doctor/create/', DoctorCreateView.as_view(), name='doctor_create'),
    path('doctor/list/', DoctorListView.as_view(), name='doctor_list'),
    path('doctor/detail/<int:pk>/', DoctorDetailView.as_view(), name='doctor_detail'),
    path('doctor/update/<int:pk>/', DoctorUpdateView.as_view(), name='doctor_update'),
    path('doctor/delete/<int:pk>/', DoctorDeleteView.as_view(), name='doctor_delete'),

    path('appointment/create/', AppointmentCreateView.as_view(), name='appointment_create'),
    path('appointment/list/', AppointmentListView.as_view(), name='appointment_list'),
    path('appointment/detail/<int:pk>/', AppointmentDetailView.as_view(), name='appointment_detail'),
    path('appointment/update/<int:pk>/', AppointmentUpdateView.as_view(), name='appointment_update'),
    path('appointment/delete/<int:pk>/', AppointmentDeleteView.as_view(), name='appointment_delete'),

    path('analysis/create/', AnalysisCreateView.as_view(), name='analysis_create'),
    path('analysis/list/', AnalysisListView.as_view(), name='analysis_list'),
    path('analysis/detail/<int:pk>/', AnalysisDetailView.as_view(), name='analysis_detail'),
    path('analysis/update/<int:pk>/', AnalysisUpdateView.as_view(), name='analysis_update'),
    path('analysis/delete/<int:pk>/', AnalysisDeleteView.as_view(), name='analysis_delete'),

    path('result/create/', ResultCreateView.as_view(), name='result_create'),
    path('result/list/', ResultListView.as_view(), name='result_list'),
    path('result/detail/<int:pk>/', ResultDetailView.as_view(), name='result_detail'),
    path('result/update/<int:pk>/', ResultUpdateView.as_view(), name='result_update'),
    path('result/delete/<int:pk>/', ResultDeleteView.as_view(), name='result_delete'),
]

main/models.py
from django.db import models

from config.settings import AUTH_USER_MODEL

NULLABLE = {'blank': True, 'null': True}

User = AUTH_USER_MODEL


class Feedback(models.Model):
    """Модель для обратной связи."""
    owner = models.ForeignKey(User, on_delete=models.CASCADE, **NULLABLE, related_name='feedbacks_owner',
                              verbose_name='владелец')
    fullname = models.CharField(max_length=150, verbose_name='Ф.И.О.')
    email = models.EmailField(verbose_name='email')
    message = models.TextField(verbose_name='сообщение')
    date_created = models.DateField(auto_now=True, verbose_name='время создания')
    is_closed = models.BooleanField(default=False, verbose_name='признак закрытости')

    class Meta:
        verbose_name = 'сообщение'
        verbose_name_plural = 'сообщения'

main/forms.py
from django.forms import BooleanField


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'

main/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

from main.models import Feedback
from services.models import Doctor
from users.models import User


class IndexTemplateView(TemplateView):
    """Контроллер для отображения главной страницы."""
    template_name = 'main/index.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Главная'
        return context_data


class AboutTemplateView(TemplateView):
    """Контроллер для отображения страницы о компании."""
    template_name = 'main/about.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'О компании'
        context_data['doctor_count'] = Doctor.objects.count()
        return context_data


class ContactsTemplateView(TemplateView):
    """Контроллер для отображения страницы контакты."""
    template_name = 'main/contacts.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Контакты'
        return context_data


def feedback(request):
    """Для отправки обратной связи."""

    user = None
    page = request.GET['page']
    status = None
    message = None

    if isinstance(request.user, User):
        user = request.user

    fullname = request.POST.get("fullname")
    email = request.POST.get("email")
    message = request.POST.get("message")

    if fullname and email and message:

        Feedback.objects.create(
            owner=user,
            fullname=fullname,
            email=email,
            message=message
        )
        status = 'success'
        message = 'Ваше сообщение успешно отправлено.'
    else:
        status = 'danger'
        message = 'Все поля должны быть заполнены.'

    return render(request, f'main/{page}.html', {'status': status, 'message': message})

main/templates/main/about.html
{% extends 'main/base.html' %}

{% block content %}
<h4>История компании</h4>
<p>
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi fringilla cursus lobortis. Morbi tristique dui neque,
  eget condimentum turpis vulputate a. Aenean eu lectus vitae purus convallis ultrices eget et justo. Nunc pulvinar,
  arcu a semper tempus, nisi mauris facilisis erat, nec porttitor dui ipsum nec ipsum. Suspendisse condimentum enim
  nulla, sit amet ornare turpis blandit eu. Donec tincidunt turpis ut accumsan posuere. Nam viverra libero dignissim
  elit consequat aliquam. Vestibulum iaculis congue ullamcorper. Morbi tristique vehicula tortor vitae sollicitudin.
  Pellentesque viverra purus ut eros tristique convallis. Phasellus efficitur dui scelerisque pretium porttitor.
</p>
<hr>
<h4>Миссия и ценности</h4>
<p>
  Ut lobortis blandit felis, at mattis nisl accumsan ut. Donec consequat pretium nisi sit amet porttitor. Proin mi elit,
  faucibus in augue nec, vehicula porttitor lacus. In fringilla vehicula massa vitae bibendum. Praesent blandit quis ex
  vel interdum. Vestibulum sollicitudin luctus nulla sit amet mattis. Nunc sed nisi finibus, lobortis massa ac,
  condimentum lorem. Phasellus laoreet nec dolor sit amet venenatis. Cras rhoncus tellus ut gravida aliquet. Phasellus
  nec urna eget mauris molestie porta at ac magna. In condimentum est lectus, sit amet fringilla velit feugiat nec.
</p>
<h4>Команда врачей</h4>
<p>
  Nullam mollis augue vitae diam condimentum maximus. Nulla facilisi. Nunc suscipit ornare ligula id egestas. Quisque
  mollis metus ac faucibus faucibus. Fusce a efficitur est.<br>
  Количество специалистов: {{ doctor_count }}
</p>
<a href="{% url 'services:doctor_list' %}">Подробный список врачей</a>
{% endblock %}

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{{ title }}</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
</head>
<body>
<div class="container">
  {% include 'main/includes/inc_navbar.html' %}
</div>
<div class="container mt-1">
  <h3>{{ title }}</h3>
</div>
<div class="container mt-3">
  {% block content %}
  {% endblock %}
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

main/templates/main/contacts.html
{% extends 'main/base.html' %}

{% block content %}
<div class="row">
  <div class="col-6">
    <h4>Адрес компании</h4>
    <p>
      Свердловская область, Екатеринбург, ул. Тургенева 3
    </p>
  </div>

  <div class="col-6">
    <h4>Контакты</h4>
    <p>
      Москва: +7-777-777-77-77<br>
      Петербург: +7-777-777-77-77<br>
      Екатеринбург: +7-777-777-77-77<br>
      Меж город: 7-77-77<br>
      Email: <a href="#">company@med.ru</a>
    </p>

  </div>
</div>
<div class="row">
  <div class="col-6">
    <script type="text/javascript" charset="utf-8" async
            src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3A07d4fc8fc6db16f7872fe698adac69afa3791fc401db13b9cdad3e597f8ada4f&amp;width=600&amp;height=450&amp;lang=ru_RU&amp;scroll=true"></script>
  </div>
  <div class="col-6">
    <form method="post" action="{% url 'main:feedback' %}?page=contacts">
      <div class="card">

        <div class="card-header">
          <h4>Обратная связь</h4>
        </div>

        <div class="card-body">
          {% csrf_token %}
          <input type="text" class="form-control" id="fullname_id" name="fullname" placeholder="Ф.И.О.">
          <input type="email" class="form-control mt-2" id="email_id" name="email" placeholder="Email">
          <input type="text" class="form-control mt-2" id="message_id" name="message" placeholder="Сообщение">
        </div>

        <div class="card-footer">
          <button class="btn btn-info" type="submit">Отправить</button>
        </div>

      </div>
    </form>

    {% if message %}
    <div class="toast align-items-center text-bg-{{ status }} mt-3" role="alert" aria-live="assertive" aria-atomic="true">
      <div class="d-flex">
        <div class="toast-body">
          {{ message }}
        </div>
        <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast"
                aria-label="Закрыть"></button>
      </div>
    </div>
    {% endif %}

  </div>
</div>

<script>
  document.addEventListener('DOMContentLoaded', function () {
    const toastElList = [].slice.call(document.querySelectorAll('.toast'))
    const toastList = toastElList.map(function (toastEl) {
      return new bootstrap.Toast(toastEl)
    })
    toastList.forEach(toast => toast.show())
  });
</script>

{% endblock %}

main/templates/main/index.html
{% extends 'main/base.html' %}

{% block content %}
<div class="row">
  <div class="col-6">
    <h5>О компании</h5>
    <p>
      Мы занимаемся диагностикой заболеваний уже много лет. У нас множество офисов по всей России. Lorem ipsum dolor sit
      amet, consectetur adipiscing elit. Morbi fringilla cursus lobortis. Morbi tristique dui neque, eget condimentum
      turpis vulputate a. Aenean eu lectus vitae purus convallis ultrices eget et justo. Nunc pulvinar, arcu a semper
      tempus, nisi mauris facilisis erat, nec porttitor dui ipsum nec ipsum. Suspendisse condimentum enim nulla, sit
      amet ornare turpis blandit eu. Donec tincidunt turpis ut accumsan posuere. Nam viverra libero dignissim elit
      consequat aliquam. Vestibulum iaculis congue ullamcorper. Morbi tristique vehicula tortor vitae sollicitudin.
      Pellentesque viverra purus ut eros tristique convallis. Phasellus efficitur dui scelerisque pretium porttitor.
    </p>
    <hr>
    <h5>Услуги</h5>
    <p>
      Сдать анализы<br>
      Записаться на прием
    </p>
  </div>

  <div class="col-6">
    <h5>Контакты</h5>
    <p>
      Москва: +7-777-777-77-77<br>
      Петербург: +7-777-777-77-77<br>
      Екатеринбург: +7-777-777-77-77<br>
      Меж город: 7-77-77
    </p>

    <form method="post" action="{% url 'main:feedback' %}?page=index">
      <div class="card">

        <div class="card-header">
          <h5>Обратная связь</h5>
        </div>

        <div class="card-body">
          {% csrf_token %}
          <input type="text" class="form-control" id="fullname_id" name="fullname" placeholder="Ф.И.О.">
          <input type="email" class="form-control mt-2" id="email_id" name="email" placeholder="Email">
          <input type="text" class="form-control mt-2" id="message_id" name="message" placeholder="Сообщение">
        </div>

        <div class="card-footer">
          <button class="btn btn-info" type="submit">Отправить</button>
        </div>

      </div>
    </form>

    {% if message %}
    <div class="toast align-items-center text-bg-{{ status }} mt-3" role="alert" aria-live="assertive" aria-atomic="true">
      <div class="d-flex">
        <div class="toast-body">
          {{ message }}
        </div>
        <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast"
                aria-label="Закрыть"></button>
      </div>
    </div>
    {% endif %}

  </div>
</div>

<script>
  document.addEventListener('DOMContentLoaded', function () {
    const toastElList = [].slice.call(document.querySelectorAll('.toast'))
    const toastList = toastElList.map(function (toastEl) {
      return new bootstrap.Toast(toastEl)
    })
    toastList.forEach(toast => toast.show())
  });
</script>

{% endblock %}