config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('users/', include('users.urls', namespace='users')),
    path('services/', include('services.urls', namespace='services')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main.apps import MainConfig
from main.views import IndexTemplateView, AboutTemplateView, ContactsTemplateView, feedback

app_name = MainConfig.name

urlpatterns = [
    path('', IndexTemplateView.as_view(), name='index'),
    path('about/', AboutTemplateView.as_view(), name='about'),
    path('contacts/', ContactsTemplateView.as_view(), name='contacts'),
    path('feedback/', feedback, name='feedback')
]

services/urls.py
from django.urls import path

from services.apps import ServicesConfig
from services.views import DoctorCreateView, DoctorListView, DoctorDetailView, DoctorUpdateView, DoctorDeleteView, \
    AppointmentCreateView, AppointmentListView, AppointmentDetailView, AppointmentUpdateView, AppointmentDeleteView, \
    AnalysisCreateView, AnalysisListView, AnalysisDetailView, AnalysisUpdateView, AnalysisDeleteView, ResultCreateView, \
    ResultListView, ResultDetailView, ResultUpdateView, ResultDeleteView

app_name = ServicesConfig.name


urlpatterns = [
    path('doctor/create/', DoctorCreateView.as_view(), name='doctor_create'),
    path('doctor/list/', DoctorListView.as_view(), name='doctor_list'),
    path('doctor/detail/<int:pk>/', DoctorDetailView.as_view(), name='doctor_detail'),
    path('doctor/update/<int:pk>/', DoctorUpdateView.as_view(), name='doctor_update'),
    path('doctor/delete/<int:pk>/', DoctorDeleteView.as_view(), name='doctor_delete'),

    path('appointment/create/', AppointmentCreateView.as_view(), name='appointment_create'),
    path('appointment/list/', AppointmentListView.as_view(), name='appointment_list'),
    path('appointment/detail/<int:pk>/', AppointmentDetailView.as_view(), name='appointment_detail'),
    path('appointment/update/<int:pk>/', AppointmentUpdateView.as_view(), name='appointment_update'),
    path('appointment/delete/<int:pk>/', AppointmentDeleteView.as_view(), name='appointment_delete'),

    path('analysis/create/', AnalysisCreateView.as_view(), name='analysis_create'),
    path('analysis/list/', AnalysisListView.as_view(), name='analysis_list'),
    path('analysis/detail/<int:pk>/', AnalysisDetailView.as_view(), name='analysis_detail'),
    path('analysis/update/<int:pk>/', AnalysisUpdateView.as_view(), name='analysis_update'),
    path('analysis/delete/<int:pk>/', AnalysisDeleteView.as_view(), name='analysis_delete'),

    path('result/create/', ResultCreateView.as_view(), name='result_create'),
    path('result/list/', ResultListView.as_view(), name='result_list'),
    path('result/detail/<int:pk>/', ResultDetailView.as_view(), name='result_detail'),
    path('result/update/<int:pk>/', ResultUpdateView.as_view(), name='result_update'),
    path('result/delete/<int:pk>/', ResultDeleteView.as_view(), name='result_delete'),
]

users/urls.py
from users.apps import UsersConfig

from django.urls import path
from django.contrib.auth.views import LogoutView
from users.views import UserLoginView, UserRegister, email_verification, UserProfile, UserProfileUpdate, CartListView, \
    add_to_cart, HistoryListView, delete_from_cart, HistoryDetailView, RequestCreateView, pay_cache

app_name = UsersConfig.name

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserRegister.as_view(), name='register'),
    path('email-confirm/<str:token>/', email_verification, name='email_confirm'),

    path('profile/', UserProfile.as_view(), name='profile'),
    path('change-profile/', UserProfileUpdate.as_view(), name='profile_update'),

    path('cart/', CartListView.as_view(), name='cart'),
    path('add_to_cart/', add_to_cart, name='add_to_cart'),
    path('delete_from_cart/', delete_from_cart, name='delete_from_cart'),
    path('pay_cache/', pay_cache, name='pay_cache'),

    path('history/', HistoryListView.as_view(), name='history'),
    path('history/detail/<int:pk>/', HistoryDetailView.as_view(), name='history_detail'),

    path('request/create/', RequestCreateView.as_view(), name='request_create'),
]

main/models.py
from django.db import models

from config.settings import AUTH_USER_MODEL

NULLABLE = {'blank': True, 'null': True}

User = AUTH_USER_MODEL


class Feedback(models.Model):
    """Модель для обратной связи."""
    owner = models.ForeignKey(User, on_delete=models.CASCADE, **NULLABLE, related_name='feedbacks_owner',
                              verbose_name='владелец')
    fullname = models.CharField(max_length=150, verbose_name='Ф.И.О.')
    email = models.EmailField(verbose_name='email')
    message = models.TextField(verbose_name='сообщение')
    date_created = models.DateField(auto_now=True, verbose_name='время создания')
    is_closed = models.BooleanField(default=False, verbose_name='признак закрытости')

    class Meta:
        verbose_name = 'сообщение'
        verbose_name_plural = 'сообщения'

main/forms.py
from django.forms import BooleanField


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'

main/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

from main.models import Feedback
from services.models import Doctor
from users.models import User


class IndexTemplateView(TemplateView):
    """Контроллер для отображения главной страницы."""
    template_name = 'main/index.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Главная'
        return context_data


class AboutTemplateView(TemplateView):
    """Контроллер для отображения страницы о компании."""
    template_name = 'main/about.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'О компании'
        context_data['doctor_count'] = Doctor.objects.count()
        return context_data


class ContactsTemplateView(TemplateView):
    """Контроллер для отображения страницы контакты."""
    template_name = 'main/contacts.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Контакты'
        return context_data


def feedback(request):
    """Для отправки обратной связи."""

    user = None
    page = request.GET['page']
    status = None
    message = None

    if isinstance(request.user, User):
        user = request.user

    fullname = request.POST.get("fullname")
    email = request.POST.get("email")
    message = request.POST.get("message")

    if fullname and email and message:

        Feedback.objects.create(
            owner=user,
            fullname=fullname,
            email=email,
            message=message
        )
        status = 'success'
        message = 'Ваше сообщение успешно отправлено.'
    else:
        status = 'danger'
        message = 'Все поля должны быть заполнены.'

    return render(request, f'main/{page}.html', {'status': status, 'message': message})

main/templates/main/includes/inc_navbar.html
<style>
  .dropdown-item:hover {
    background-color: #b6d4fe;
    color: #000;
    transition: 0.3s;
  }
</style>

<nav class="navbar navbar-expand-lg" style="background-color: #e3f2fd;">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'main:index' %}">Главная</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav me-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button">Услуги</a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'services:analysis_list' %}">Анализы</a></li>
            <li><a class="dropdown-item" href="{% url 'services:appointment_list' %}">Прием врача</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'main:contacts' %}">Контакты</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'main:about' %}">О компании</a>
        </li>
      </ul>
      <ul class="navbar-nav">
        <li class="nav-item dropdown ms-auto">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            {% if user.is_authenticated %}
            {{ user }}
            {% else %}
            Личный кабинет
            {% endif %}
          </a>
          <ul class="dropdown-menu dropdown-menu-end">
            {% if user.is_authenticated %}
            {% if user.is_superuser %}
            <li><a class="dropdown-item" href="/admin/">Админка</a></li>
            {% endif %}
            <li><a class="dropdown-item" href="{% url 'users:profile' %}">Профиль</a></li>
            <li><a class="dropdown-item" href="{% url 'users:history' %}">История</a></li>
            <li><a class="dropdown-item" href="{% url 'users:logout' %}">Выйти</a></li>
            {% else %}
            <li><a class="dropdown-item" href="{% url 'users:login' %}">Войти</a></li>
            <li><a class="dropdown-item" href="{% url 'users:register' %}">Регистрация</a></li>
            {% endif %}
          </ul>
        </li>
      </ul>
      <a class="nav-link me-2" href="{% url 'users:cart' %}">
        <img src="https://www.iconsdb.com/icons/preview/green/shopping-cart-xxl.png" style="width: 30px; height: 30px;">
      </a>
    </div>
  </div>
</nav>

main/templates/main/includes/inc_paginator.html
        <nav aria-label="Page navigation">
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page=1" aria-label="First">
        &laquo;
      </a>
    </li>
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
        <
      </a>
    </li>
    {% endif %}

    <li class="page-item active" aria-current="page">
      <span class="page-link">
        {{ page_obj.number }}
      </span>
    </li>

    {% if page_obj.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
        >
      </a>
    </li>
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Last">
        &raquo;
      </a>
    </li>
    {% endif %}
  </ul>
</nav>