config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('users/', include('users.urls', namespace='users')),
    path('services/', include('services.urls', namespace='services')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main.apps import MainConfig
from main.views import IndexTemplateView, AboutTemplateView, ContactsTemplateView, feedback

app_name = MainConfig.name

urlpatterns = [
    path('', IndexTemplateView.as_view(), name='index'),
    path('about/', AboutTemplateView.as_view(), name='about'),
    path('contacts/', ContactsTemplateView.as_view(), name='contacts'),
    path('feedback/', feedback, name='feedback')
]

services/urls.py
from django.urls import path

from services.apps import ServicesConfig
from services.views import DoctorCreateView, DoctorListView, DoctorDetailView, DoctorUpdateView, DoctorDeleteView, \
    AppointmentCreateView, AppointmentListView, AppointmentDetailView, AppointmentUpdateView, AppointmentDeleteView, \
    AnalysisCreateView, AnalysisListView, AnalysisDetailView, AnalysisUpdateView, AnalysisDeleteView, ResultCreateView, \
    ResultListView, ResultDetailView, ResultUpdateView, ResultDeleteView

app_name = ServicesConfig.name


urlpatterns = [
    path('doctor/create/', DoctorCreateView.as_view(), name='doctor_create'),
    path('doctor/list/', DoctorListView.as_view(), name='doctor_list'),
    path('doctor/detail/<int:pk>/', DoctorDetailView.as_view(), name='doctor_detail'),
    path('doctor/update/<int:pk>/', DoctorUpdateView.as_view(), name='doctor_update'),
    path('doctor/delete/<int:pk>/', DoctorDeleteView.as_view(), name='doctor_delete'),

    path('appointment/create/', AppointmentCreateView.as_view(), name='appointment_create'),
    path('appointment/list/', AppointmentListView.as_view(), name='appointment_list'),
    path('appointment/detail/<int:pk>/', AppointmentDetailView.as_view(), name='appointment_detail'),
    path('appointment/update/<int:pk>/', AppointmentUpdateView.as_view(), name='appointment_update'),
    path('appointment/delete/<int:pk>/', AppointmentDeleteView.as_view(), name='appointment_delete'),

    path('analysis/create/', AnalysisCreateView.as_view(), name='analysis_create'),
    path('analysis/list/', AnalysisListView.as_view(), name='analysis_list'),
    path('analysis/detail/<int:pk>/', AnalysisDetailView.as_view(), name='analysis_detail'),
    path('analysis/update/<int:pk>/', AnalysisUpdateView.as_view(), name='analysis_update'),
    path('analysis/delete/<int:pk>/', AnalysisDeleteView.as_view(), name='analysis_delete'),

    path('result/create/', ResultCreateView.as_view(), name='result_create'),
    path('result/list/', ResultListView.as_view(), name='result_list'),
    path('result/detail/<int:pk>/', ResultDetailView.as_view(), name='result_detail'),
    path('result/update/<int:pk>/', ResultUpdateView.as_view(), name='result_update'),
    path('result/delete/<int:pk>/', ResultDeleteView.as_view(), name='result_delete'),
]

users/urls.py
from users.apps import UsersConfig

from django.urls import path
from django.contrib.auth.views import LogoutView
from users.views import UserLoginView, UserRegister, email_verification, UserProfile, UserProfileUpdate, CartListView, \
    add_to_cart, HistoryListView, delete_from_cart, HistoryDetailView, RequestCreateView, pay_cache

app_name = UsersConfig.name

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserRegister.as_view(), name='register'),
    path('email-confirm/<str:token>/', email_verification, name='email_confirm'),

    path('profile/', UserProfile.as_view(), name='profile'),
    path('change-profile/', UserProfileUpdate.as_view(), name='profile_update'),

    path('cart/', CartListView.as_view(), name='cart'),
    path('add_to_cart/', add_to_cart, name='add_to_cart'),
    path('delete_from_cart/', delete_from_cart, name='delete_from_cart'),
    path('pay_cache/', pay_cache, name='pay_cache'),

    path('history/', HistoryListView.as_view(), name='history'),
    path('history/detail/<int:pk>/', HistoryDetailView.as_view(), name='history_detail'),

    path('request/create/', RequestCreateView.as_view(), name='request_create'),
]

services/models.py
from django.db import models

from main.models import NULLABLE
from config.settings import AUTH_USER_MODEL

User = AUTH_USER_MODEL


class Speciality(models.Model):
    """Модель специальность."""
    owner = models.ForeignKey(User, on_delete=models.CASCADE, **NULLABLE, related_name='specialities_owner',
                              verbose_name='владелец')
    title = models.CharField(max_length=300, verbose_name='наименование')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'специальность'
        verbose_name_plural = 'специальности'


class Doctor(models.Model):
    """Модель врача, врач не является пользователем сайта."""
    owner = models.ForeignKey(User, on_delete=models.CASCADE, **NULLABLE, related_name='doctors_owner',
                              verbose_name='владелец')
    fullname = models.CharField(max_length=150, verbose_name='Ф.И.О.')
    speciality = models.ForeignKey(Speciality, on_delete=models.SET_NULL, **NULLABLE, verbose_name='специальность')
    education = models.TextField(verbose_name='образование')
    information = models.TextField(**NULLABLE, verbose_name='общая информация')
    avatar = models.ImageField(upload_to='services/avatars', default='avatar_placeholder.jpg', **NULLABLE,
                               verbose_name='аватар')

    experience = models.PositiveSmallIntegerField(verbose_name='стаж')

    def __str__(self):
        return self.fullname

    class Meta:
        verbose_name = 'врач'
        verbose_name_plural = 'врачи'


class Appointment(models.Model):
    """Модель записи на прием ко врачу."""
    owner = models.ForeignKey(User, on_delete=models.CASCADE, **NULLABLE, related_name='appointments_owner',
                              verbose_name='владелец')
    title = models.CharField(max_length=200, verbose_name='название')

    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE, **NULLABLE, related_name='appointments_doctor',
                               verbose_name='врач')

    date_time = models.DateTimeField(**NULLABLE, verbose_name='дата и время приема')
    treatment_room = models.PositiveSmallIntegerField(verbose_name='процедурный кабинет')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'прием'
        verbose_name_plural = 'приемы'
        ordering = ('doctor',)


class UsersAppointment(models.Model):
    """Модель записи на прием пользователя, пользователь выбирает какие услуги будут на приеме,
     после создания объект отправляется в корзину."""
    owner = models.ForeignKey(User, on_delete=models.CASCADE, **NULLABLE, related_name='users_appointments_owner',
                              verbose_name='владелец')
    title = models.CharField(max_length=200, verbose_name='название')

    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE, **NULLABLE, related_name='users_appointments_doctor',
                               verbose_name='врач')

    date_time = models.DateTimeField(**NULLABLE, verbose_name='дата и время приема')

    service_id = models.PositiveIntegerField(**NULLABLE, verbose_name='id услуги')

    def __str__(self):
        return self.title

    def get_service(self):
        pk = self.service_id
        service = Service.objects.get(pk=pk)
        return service

    class Meta:
        verbose_name = 'пользовательский прием'
        verbose_name_plural = 'пользовательские приемы'


class Service(models.Model):
    """Модель услуги на приеме."""
    owner = models.ForeignKey(User, on_delete=models.CASCADE, **NULLABLE, related_name='services_owner',
                              verbose_name='владелец')
    title = models.CharField(max_length=200, verbose_name='название')
    description = models.TextField(verbose_name='описание')
    preparation = models.TextField(default='Особой подготовки не требуется.', verbose_name='подготовка')
    price = models.PositiveSmallIntegerField(verbose_name='цена')

    appointment = models.ForeignKey(Appointment, on_delete=models.SET_NULL, **NULLABLE,
                                    related_name='services_appointment', verbose_name='запись')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'услуга'
        verbose_name_plural = 'услуги'
        ordering = ('price',)


class Analysis(models.Model):
    """Модель анализа."""
    owner = models.ForeignKey(User, on_delete=models.CASCADE, **NULLABLE, related_name='analyses_owner',
                              verbose_name='владелец')
    title = models.CharField(max_length=200, verbose_name='название')
    description = models.TextField(verbose_name='описание')
    preparation = models.TextField(default='Особой подготовки не требуется.', verbose_name='подготовка')

    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE, **NULLABLE, related_name='analyses_doctor',
                               verbose_name='врач')

    date_time = models.DateTimeField(**NULLABLE, verbose_name='дата и время приема')
    treatment_room = models.PositiveSmallIntegerField(verbose_name='процедурный кабинет')
    price = models.PositiveSmallIntegerField(verbose_name='цена')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'анализ'
        verbose_name_plural = 'анализы'
        ordering = ('price',)


class Result(models.Model):
    """Модель результата анализа или диагноза на приеме."""
    owner = models.ForeignKey(User, on_delete=models.CASCADE, **NULLABLE, related_name='results_owner',
                              verbose_name='владелец')
    title = models.CharField(max_length=200, verbose_name='название')

    analysis = models.ForeignKey(Analysis, on_delete=models.SET_NULL, **NULLABLE, related_name='results_analysis',
                                 verbose_name='анализ')
    appointment = models.ForeignKey(Appointment, on_delete=models.SET_NULL, **NULLABLE,
                                    related_name='results_appointment', verbose_name='прием')

    message = models.TextField(help_text='Результат анализа или диагноз приема', verbose_name='сообщение')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'результат'
        verbose_name_plural = 'результаты'

services/forms.py
from django.forms import ModelForm

from main.forms import StyleFormMixin
from services.models import Doctor, Appointment, Analysis, Result


class DoctorModelForm(StyleFormMixin, ModelForm):
    """Форма для создания/редактирования объекта модели Doctor."""
    class Meta:
        model = Doctor
        exclude = ('owner',)


class AppointmentModelForm(StyleFormMixin, ModelForm):
    """Форма для создания/редактирования объекта модели Doctor."""
    class Meta:
        model = Appointment
        exclude = ('owner',)


class AnalysisModelForm(StyleFormMixin, ModelForm):
    """Форма для создания/редактирования объекта модели Analysis."""

    class Meta:
        model = Analysis
        exclude = ('owner',)


class ResultModelForm(StyleFormMixin, ModelForm):
    """Форма для создания/редактирования объекта модели Result."""

    class Meta:
        model = Result
        exclude = ('owner',)

services/templates/services/analysis_confirm_delete.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="card mt-4">
      <div class="card-header">
        <h6>{{ object.title }}</h6>
      </div>
      <div class="card-body" style="height:50px">
        <p>{{ object.price }}</p>
      </div>
      <div class="card-footer">
         <div class="row col-12">
        <div class="col-6 p-1">
          <form method="post">
            {% csrf_token %}
            <button class="btn btn-outline-danger col-12">Удалить</button>
          </form>
        </div>
            <div class="col-6 p-1">
            <a class="btn btn-outline-primary col-12" href="{% url 'services:analysis_list' %}">К списку анализов</a>
          </div>
      </div>
    </div>
{% endblock %}

services/templates/services/analysis_detail.html
{% extends 'main/base.html' %}
{% load custom_tags %}

{% block content %}
<div class="row">

  <div class="col-9">
    <h4>{{ object.title }}</h4>
    <h6>Описание</h6>
    <p>{{ object.description }}</p>
    <hr>
    <h6>Подготовка</h6>
    <p>{{ object.preparation }}</p>
    <hr>
    <h6>Цена</h6>
    <p>{{ object.price }} ₽</p>
  </div>

  <div class="col-3">
    <div class="col-12">
      <div class="col-12 mt-2">
        <a class="btn btn-outline-primary col-12" href="{% url 'services:analysis_list' %}">К списку анализов</a>
      </div>
      {% if perms.services.change_analysis and perms.services.delete_analysis %}
      <div class="row p-2">
        <div class="col-6 p-1">
          <a class="btn btn-outline-primary col-12" href="{% url 'services:analysis_update' object.pk %}">Изменить</a>
        </div>
        <div class="col-6 p-1">
          <a class="btn btn-outline-primary col-12" href="{% url 'services:analysis_delete' object.pk %}">Удалить</a>
        </div>
      </div>
      {% endif %}
    </div>
  </div>

</div>
{% endblock %}

services/templates/services/analysis_form.html
{% extends 'main/base.html' %}

{% block content %}
<div class="col-12">
  <div class="card mt-5">
    <div class="card-header">
      Анализ
    </div>
    <form method="post" enctype="multipart/form-data">
      <div class="card-body">
        {% csrf_token %}
        {{ form.as_p }}
      </div>
      <div class="card-footer">
        <div class="row col-4">
          {% if object %}
            <div class="col-6 p-1">
              <button class="btn btn-outline-success col-12">Сохранить</button>
            </div>
          {% else %}
            <div class="col-6 p-1">
              <button class="btn btn-outline-success col-12">Создать</button>
            </div>
          {% endif %}
          <div class="col-6 p-1">
            <a class="btn btn-outline-primary col-12" href="{% url 'services:analysis_list' %}">К списку анализов</a>
          </div>
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock %}

services/templates/services/appointment_confirm_delete.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="card mt-4">
      <div class="card-header">
        <h6>{{ object.title }}</h6>
      </div>
      <div class="card-body" style="height:50px">
        <p>{{ object.price }}</p>
      </div>
      <div class="card-footer">
         <div class="row col-12">
        <div class="col-6 p-1">
          <form method="post">
            {% csrf_token %}
            <button class="btn btn-outline-danger col-12">Удалить</button>
          </form>
        </div>
            <div class="col-6 p-1">
            <a class="btn btn-outline-primary col-12" href="{% url 'services:appointment_list' %}">К списку приемов</a>
          </div>
      </div>
    </div>
{% endblock %}

services/templates/services/appointment_detail.html
{% extends 'main/base.html' %}

{% block content %}

<div class="container mt-3 p-0">
  <div class="row">
    <div class="row">
      <div class="col-10">
        <div class="d-flex w-100 justify-content-between">
          <h5 class="mb-1">{{ object.title }}</h5>
          <small class="text-muted">3 дня назад</small>
        </div>
        <hr>
        <p>{{ object.doctor }}</p>
        <div class="col-2 text-end">
          <div class="d-flex justify-content-between align-items-center h-100">
            <div class="vr"></div>
            <p class="mb-1">
              {{ object.description }}<br>
            </p>

          </div>
        </div>
      </div>

      <div class="col-2 text-end">
        <div class="d-flex justify-content-between align-items-center h-100">
          <div class="vr"></div>

          <div class="ms-3">
            <h4>{{ object.price }} ₽ <a href="#" class="btn btn-info">+</a></h4>
          </div>
        </div>
      </div>

    </div>

    <div class="container p-0">
      {% for service in object.services_appointment.all %}
      <div class="card">
        <div class="card-body">
      {{ service }} <h4>{{ service.price }} ₽ <a href="#" class="btn btn-info">+</a></h4><br>
      </div>
      </div>
      {% endfor %}
    </div>


  </div>
</div>
{% endblock %}

services/templates/services/appointment_form.html
{% extends 'main/base.html' %}

{% block content %}
<div class="container p-0">
  <div class="row mt-5 p-0">
    <div class="col-md-6 p-0">
      <div class="card">
        <div class="card-header">
          Прием
        </div>
        <div class="card-body">
          <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="row mt-3">
              {% if object %}
              <div class="col-6 p-1">
                <button class="btn btn-outline-success col-12">Сохранить</button>
              </div>
              {% else %}
              <div class="col-6 p-1">
                <button class="btn btn-outline-success col-12">Создать</button>
              </div>
              {% endif %}
              <div class="col-6 p-1">
                <a class="btn btn-outline-primary col-12" href="{% url 'services:doctor_list' %}">К списку приемов</a>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>

    <div class="col-md-6 p-0">
      {% if object %}
      <div class="card">
        <div class="card-header">
          Услуга
        </div>
        {{ formset.management_form }}
        {% for form in formset.forms %}
        <div class="card-body">
          {{ form.as_p }}
          <hr>
        </div>
        {% endfor %}
      </div>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

services/templates/services/appointment_list.html
{% extends 'main/base.html' %}
{% load custom_tags %}

{% block content %}
{% if perms.services.add_doctor %}
<div class="container p-0">
  <a class="btn btn-primary" href="{% url 'services:appointment_create' %}">Добавить Прием</a>
</div>
{% endif %}
<div class="container mt-3 p-0">
  <div class="row">

    <div class="col-3">
      <div class="h-100">
        <div class="card p-1">
          <div class="row m-0 p-0">
            <a class="btn btn-outline-info mb-1" href="{% url 'services:appointment_list' %}">
              Все специальности
            </a>
            {% for speciality in specialities %}
            <a class="btn btn-outline-info mb-1" href="?speciality_pk={{ speciality.pk }}">
              {{ speciality }}
            </a>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>

    <div class="col-9">
      {% for object in page_obj %}
      <div class="list-group">

        <div class="list-group-item list-group-item-action mb-1">
          <div class="row">

            <div class="col-2">
              <img src="{{ object.avatar | media_filter }}" style="width: 8rem; height: 8rem;"
                   border="1px solid #555"><br>
              <h6>{{ object.doctor.fullname }}</h6>
              <small>Стаж {{ object.doctor.experience|years_declination_filter }}</small>
            </div>

            <div class="col-8">
              <h5 class="mb-1">{{ object.doctor.speciality }}</h5>

              <div class="accordion mt-2" id="accordionAppointment">
                <div class="accordion-item">
                  <h2 class="accordion-header">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                            data-bs-target="#collapse{{ object.pk }}"
                            aria-expanded="true" aria-controls="collapse{{ object.pk }}">
                      Выберите услугу
                    </button>
                  </h2>
                  <div id="collapse{{ object.pk }}" class="accordion-collapse collapse"
                       data-bs-parent="#accordionAppointment">

                    <div class="accordion-body">
                      <div class="overflow-y-scroll" style="max-height: 200px">
                        {% for service in object.services_appointment.all %}
                        <div class="container w-100">
                          <div class="form-check d-flex align-items-center w-100">
                            <input class="form-check-input" type="radio" name="flexRadioService{{ object.pk }}"
                                   id="flexRadioService{{ service.pk }}">
                            <label class="form-check-label w-100 d-flex align-items-center"
                                   for="flexRadioService{{ service.pk }}">
                              <div class="card mb-1 ms-1 w-100" style="height: 40px">
                                <div class="d-flex w-100 justify-content-between align-items-center h-100">
                                  <h6 class="ms-2 mb-0">{{ service.title }}</h6>
                                  <strong class="me-2 mb-0">{{ service.price }} ₽</strong>
                                </div>
                              </div>
                            </label>
                          </div>
                        </div>
                        {% endfor %}
                      </div>
                    </div>

                  </div>
                </div>
              </div>
            </div>

            <div class="col-2 text-end">
              <div class="d-flex justify-content-between h-100">
                <div class="vr"></div>
                <h4>
                  <button class="btn btn-info" onclick="add_to_cart({{ object.pk }})">Записаться</button>
                </h4>
              </div>
            </div>

          </div>
        </div>
      </div>
      {% endfor %}
    </div>

    {% include 'main/includes/inc_paginator.html' %}

  </div>
</div>

<script>
  function add_to_cart(appointmentId) {
      const isAuthenticated = {{ request.user.is_authenticated|yesno:"true,false" }};

      if (!isAuthenticated) {
          window.location.href = "{% url 'users:login' %}";
          return;
      }

      const selectedService = document.querySelector(`input[name="flexRadioService${appointmentId}"]:checked`);

      if (!selectedService) {
          alert("Пожалуйста, выберите услугу для этого приема перед добавлением в корзину.");
          return;
      }

      const serviceId = selectedService.id.replace('flexRadioService', '');

      fetch("{% url 'users:add_to_cart' %}?type=appointment&appointment_id=" + appointmentId + "&service_id=" + serviceId, {
          method: 'GET',}).then(response => {
      });
  }
</script>

{% endblock %}

services/templates/services/doctor_confirm_delete.html
{% extends 'main/base.html' %}
{% block content %}
    <div class="card mt-4">
      <div class="card-header">
        <h6>{{ object.fullname }}</h6>
      </div>
      <div class="card-body" style="height:50px">
        <p>{{ object.speciality }}</p>
      </div>
      <div class="card-footer">
         <div class="row col-12">
        <div class="col-6 p-1">
          <form method="post">
            {% csrf_token %}
            <button class="btn btn-outline-danger col-12">Удалить</button>
          </form>
        </div>
            <div class="col-6 p-1">
            <a class="btn btn-outline-primary col-12" href="{% url 'services:doctor_list' %}">К списку врачей</a>
          </div>
      </div>
    </div>
{% endblock %}

services/templates/services/doctor_detail.html
{% extends 'main/base.html' %}
{% load custom_tags %}

{% block content %}
<div class="row">
  <div class="col-4">
    <img src="{{ object.avatar | media_filter }}" style="width: 26rem; height: 26rem;" border="1px solid #555">
    <div class="col-12">
      <div class="col-12 mt-2">
        <a class="btn btn-outline-primary col-12" href="{% url 'services:doctor_list' %}">К списку врачей</a>
      </div>
      {% if perms.services.change_doctor and perms.services.delete_doctor %}
      <div class="row p-2">
        <div class="col-6 p-1">
          <a class="btn btn-outline-primary col-12" href="{% url 'services:doctor_update' object.pk %}">Изменить</a>
        </div>
        <div class="col-6 p-1">
          <a class="btn btn-outline-primary col-12" href="{% url 'services:doctor_delete' object.pk %}">Удалить</a>
        </div>
      </div>
      {% endif %}
    </div>
  </div>
  <div class="col-8">
    <h4>{{ object.fullname }}</h4>
    <hr>
    <h6>Специальность</h6>
    <p>
      {{ object.speciality }}
    </p>
    <hr>
    <h6>Образование</h6>
    <p>
      {{ object.education }}
    </p>
    <hr>
    <h6>Стаж работы</h6>
    <p>
      {{ object.experience|years_declination_filter }}
    </p>
    <hr>
    {% if object.information %}
    <h6>Дополнительная информация</h6>
    <p>
      {{ object.information }}
    </p>
    <hr>
    {% endif %}
  </div>
</div>


{% endblock %}

services/templates/services/doctor_form.html
{% extends 'main/base.html' %}
{% block content %}
<div class="col-12">
  <div class="card mt-5">
    <div class="card-header">
      Врач
    </div>
    <form method="post" enctype="multipart/form-data">
      <div class="card-body">
        {% csrf_token %}
        {{ form.as_p }}
      </div>
      <div class="card-footer">
        <div class="row col-4">
          {% if object %}
            <div class="col-6 p-1">
              <button class="btn btn-outline-success col-12">Сохранить</button>
            </div>
          {% else %}
            <div class="col-6 p-1">
              <button class="btn btn-outline-success col-12">Создать</button>
            </div>
          {% endif %}
          <div class="col-6 p-1">
            <a class="btn btn-outline-primary col-12" href="{% url 'services:doctor_list' %}">К списку врачей</a>
          </div>
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock %}

services/templates/services/doctor_list.html
{% extends 'main/base.html' %}
{% load custom_tags %}

{% block content %}
{% if perms.services.add_doctor %}
<div class="container p-0">
  <a class="btn btn-primary" href="{% url 'services:doctor_create' %}">Добавить Врача</a>
</div>
{% endif %}
<div class="row">
  {% for object in object_list %}
  <div class="col-2">
    <div class="card text-center mt-3">
      <div class="card-header p-0" style="height:45px">
        <a href="{% url 'services:doctor_detail' object.pk %}">
          <h6>{{ object.fullname|truncatechars:40 }}</h6>
        </a>
      </div>
      <div class="card-body" style="height:255px">
        <img src="{{ object.avatar | media_filter }}" style="width: 10rem; height: 10rem;" border="1px solid #555">
        <h6>Специальность:</h6>
        <p>{{ object.speciality|truncatechars:30 }}</p>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}

services/templates/services/result_confirm_delete.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="card mt-4">
      <div class="card-header">
        <h6>{{ object.title }}</h6>
      </div>
      <div class="card-body" style="height:70px">
        <p>{{ object.appointment }}<br>
          {{ object.analysis }}
        </p>
      </div>
      <div class="card-footer">
         <div class="row col-12">
        <div class="col-6 p-1">
          <form method="post">
            {% csrf_token %}
            <button class="btn btn-outline-danger col-12">Удалить</button>
          </form>
        </div>
            <div class="col-6 p-1">
            <a class="btn btn-outline-primary col-12" href="{% url 'services:result_list' %}">К списку результатов</a>
          </div>
      </div>
    </div>
{% endblock %}

services/templates/services/result_form.html
{% extends 'main/base.html' %}

{% block content %}
<div class="col-12">
  <div class="card mt-5">
    <div class="card-header">
      Результат
    </div>
    <form method="post" enctype="multipart/form-data">
      <div class="card-body">
        {% csrf_token %}
        {{ form.as_p }}
      </div>
      <div class="card-footer">
        <div class="row col-4">
          {% if object %}
            <div class="col-6 p-1">
              <button class="btn btn-outline-success col-12">Сохранить</button>
            </div>
          {% else %}
            <div class="col-6 p-1">
              <button class="btn btn-outline-success col-12">Создать</button>
            </div>
          {% endif %}
          <div class="col-6 p-1">
            <a class="btn btn-outline-primary col-12" href="{% url 'services:result_list' %}">К списку результатов</a>
          </div>
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock %}

services/templates/services/result_list.html
{% extends 'main/base.html' %}
{% load custom_tags %}

{% block content %}
{% if perms.services.add_result %}
<div class="container p-0">
  <a class="btn btn-primary" href="{% url 'services:result_create' %}">Добавить Результат</a>
</div>
{% endif %}
<div class="container mt-3 p-0">
  <div class="row">
    <div class="col-3">
      <div class="h-100">
        <div class="card p-1">
          <p>Разделы</p>
        </div>
      </div>
    </div>

    <div class="col-9">
      {% for object in object_list %}
      <div class="list-group">

        <div class="list-group-item mb-2" style="min-height: 120px">
          <div class="row">
            <div class="col-10">
              <h5 class="mb-1">
                <a href="{% url 'services:result_detail' object.pk %}">{{ object.title|truncatechars:85 }}</a>
              </h5>
              <p class="mb-1">
                {{ object.description|truncatechars:250 }}<br>
              </p>
            </div>

            <div class="col-2 text-end">
              <div class="d-flex justify-content-between h-100">
                <div class="vr"
                     style="position: absolute; left: 83%; top: 0; bottom: 0; width: 1px; background-color: #ccc;"></div>

                <div class="d-flex w-100 justify-content-between">
                  <h4 class="mb-1">{{ object.price }} ₽</h4>
                  <h4><a href="#" class="btn btn-info">+</a></h4>
                </div>

              </div>
            </div>

          </div>
        </div>
      </div>
      {% endfor %}
    </div>

  </div>
</div>
{% endblock %}